#!/bin/bash

MLW_DEST=${MLW_DEST:-dest}
MLW_ISO=${MLW_ISO:-modian-example.iso}
MLW_MIRROR=${MLW_MIRROR:-https://cdn-fastly.deb.debian.org/debian}
MLW_ISO_VOLUME=${MLW_ISO_VOLUME:-modian-example}
MLW_DESCRIPTION=${MLW_DESCRIPTION:-"Modian Example"}

FILELOG=${MLW_DEST}//modian-example-$(date "+%Y%m%d_%H%M%S").log

live-wrapper/lwr.py \
    --architecture=amd64 \
    -o ${MLW_DEST}/${MLW_ISO} \
    --distribution=buster \
    --mirror=${MLW_MIRROR} \
    --apt-mirror=${MLW_MIRROR} \
    --apt-mirror-components="main" \
    --volume-id="${MLW_ISO_VOLUME}" \
    --description="${MLW_DESCRIPTION}" \
    --playbook="ansible/chroot.yaml" \
    --bootappend="consoleblank=0 debug" \
    --networkd \
    --boot-timeout=1 \
    --cache-dir=cache/ \
    --customize-squashfs="customize/squashfs.sh" \
    --squashfs-comp="lzo" \
    --work-dir="build" \
    --no-installer  |& tee -a $FILELOG
