# Get modian packages from a repository served by ``./local_repo.py serve``
modian_repo: '[trusted=yes] http://localhost:8099/'
modian_system_modes:
 - name: kiosk
   description: Locked down kiosk mode
   documentation: https://docs.example.org/system-modes/kiosk
 - name: maint
   description: Maintenance mode
