---
- name: Install ansible dependency
  apt:
    name: python3-debian
    state: present
- name: Install modian packages, adding the repo if needed
  block:
    - name: Add the modian repo
      deb822_repository:
        name: modian
        types: deb
        uris: "{{ modian_repo_uris }}"
        suites: "{{ modian_repo_suites }}"
        trusted: true
        components:
          - main
      when: modian_repo_uris is defined and modian_repo_uris and modian_repo_trusted
    - name: Add the modian repo
      deb822_repository:
        name: modian
        types: deb
        uris: "{{ modian_repo_uris }}"
        components:
          - main
        signed-by: "{{ modian_repo_key }}"
      when: modian_repo_uris is defined and modian_repo_uris and not modian_repo_trusted
    - name: Add the modian repository key, if needed
      copy:
        src: "{{ modian_repo_key }}"
        dest: "/usr/share/keyrings/{{ modian_repo_key }}"
      when: modian_repo_key is defined and modian_repo_key
    - name: Add the modian repository
      apt_repository:
        repo: 'deb {{ modian_repo }} {{ distribution }} main'
        state: present
      when: modian_repo is defined and modian_repo
    - name: Install modian packages
      apt:
        name: modian-install,python3-modian
        state: present
        update_cache: true
    - name: install patches for live boot
      apt:
        name: modian-live-boot-patches
        state: present
      when: ansible_distribution_release == "bookworm" or
            ansible_distribution_release == "trixie"
  rescue:
    - name: Fail with an explanation
      fail:
        msg: "We could not install the modian packages; the reason may be that the variable modian_repo is not set or is set to false: please set it to a repository that includes the modian packages, or configure such a repository in some other way in a role that runs before the modian role."
      when: modian_repo is not defined or not modian_repo
    - name: Fail
      fail:
        msg: "We could not install the modian packages: see the error messages above for details."
