---
  - name: legacy system configuration file
    copy:
      src: "{{ legacy_conf }}"
      dest: /etc/modian/legacy.yaml

  - name: install virtualization packages
    apt:
      name: qemu-system-x86,qemu-utils
      state: present

  - name: install X and a dm to show the virtualized image
    apt:
      name: "{{ legacy_host_dm }}"
      state: present

  - name: install dependencies of the modian-legacy script
    apt:
      name: python3-ruamel.yaml
      state: present

  - name: qemu configuration directory
    file:
      path: /etc/qemu
      state: directory

  - name: qemu bridge whitelist
    template:
      src: bridge.conf
      dest: /etc/qemu/bridge.conf
      mode: 0640

  - name: prepare the directory for images
    # the user should be able to write files for the kernel (and by default the
    # persistence file) in this directory.
    file:
      path: /srv/iso
      state: directory
      owner: root
      group: root
      mode: 0775

  - name: get the iso basename
    set_fact:
      iso_filename: "{{ legacy_guest_iso | basename }}"

  - name: copy the iso inside the image
    copy:
      src: "{{ legacy_guest_iso }}"
      dest: "/srv/iso/{{ iso_filename }}"

  - name: copy the qemu startup script
    copy:
      src: modian-legacy
      dest: /usr/bin/modian-legacy
      mode: 0755
      owner: root
      group: root

  - name: "Create user unit modian-legacy.target" 
    copy:
      src: modian-legacy.target
      dest: "/lib/systemd/user/modian-legacy.target"
      mode: 0755
      owner: root
      group: root

  - name: "Create user unit modian-legacy.service" 
    copy:
      src: modian-legacy.service
      dest: "/lib/systemd/user/modian-legacy.service"
      mode: 0755
      owner: root
      group: root

  # Enabling the service with become doesn't work, so we create the symlink by
  # hand.
  - name: "Check for the systemd unit directories"
    file:
      path: "/home/{{ live_user }}/.config/systemd/user/modian-legacy.target.wants/"
      state: directory

  - name: "Enable user unit modian-legacy.service"
    file:
      state: link
      path: "/home/{{ live_user }}/.config/systemd/user/modian-legacy.target.wants/modian-legacy.service"
      src: "/usr/lib/systemd/user/modian-legacy.service"

  - name: Make sure /etc/X11 exists
    file:
      path: /etc/X11
      state: directory
      mode: 0755
      owner: root
      group: root

  - name: Make sure /etc/X11/Xsession.d exists
    file:
      path: /etc/X11/Xsession.d
      state: directory
      mode: 0755
      owner: root
      group: root

  - name: Add Xsession hook
    copy:
      src: xsession-hook
      dest: /etc/X11/Xsession.d/99modian-legacy
      mode: 0755
      owner: root
      group: root
