---
  - name: install virtualization packages
    apt:
      name: qemu-system-x86,qemu-utils
      state: present

  - name: install X and a dm to show the virtualized image
    apt:
      name: "{{ legacy_host_dm }}"
      state: present

  - name: prepare the directory for images
    file:
      path: /srv/iso
      state: directory

  - name: get the iso basename
    set_fact:
      iso_filename: "{{ legacy_guest_iso | basename }}"

  - name: copy the iso inside the image
    copy:
      src: "{{ legacy_guest_iso }}"
      dest: "/srv/iso/{{ iso_filename }}"

  - name: copy the quest startup script
    copy:
      src: modian-legacy
      dest: /usr/bin/modian-legacy
      mode: 0755
      owner: root
      group: root
