#!/usr/bin/python3

import logging
import sys
import os
import re
import shlex

import modian_install

log = logging.getLogger()

VERSION = "1.0"

LABEL_ROOT = "##root##"
LABEL_LOG = "##log##"
LABEL_DATA = "##data##"
LABEL_IMAGES = "##images##"
LABEL_ESP = (
    "##ESP##"  # Not really a disk label, but used to identify ESP partition
)


class System(modian_install.hardware.System):
    def __init__(self, hardware):
        super().__init__(hardware)
        self.disk_img = None

        self.LABELS["data"] = "##data##"
        self.LABELS["images"] = "##images##"

    def read_additional_partition_labels(self):
        ok = True
        ok = self._check_partition(self.LABELS["data"], self.disk_root) and ok
        ok = self._check_partition(self.LABELS["images"], self.disk_img) and ok
        return ok

    def select_disks(self):
        ok, devs = super().select_disks()
        if len(devs) > 2:
            log.error("%d disks found, refusing to choose", len(devs))
            ok = False
        if len(devs) > 1:
            if devs[0].size == devs[1].size:
                self.disk_img = devs[1]
                log.info(
                    "Selected %s as image, as the second name of the two",
                    self.disk_img,
                )
            else:
                self.disk_img = devs[1]
                log.info(
                    "Selected %s as image, as the biggest of two",
                    self.disk_img,
                )
        return ok, devs

    def log_found_devices(self):
        log.info(
            "Root device: %s (%s)", self.disk_root.name, self.disk_root.details
        )
        if self.disk_img is None:
            log.info("Image device: not found")
        else:
            log.info(
                "Image device: %s (%s)",
                self.disk_img.name,
                self.disk_img.details,
            )
        log.info(
            "Installation media: %s (%s)",
            self.disk_inst.name,
            self.disk_inst.details,
        )

        self._read_partition_labels()
        log.info(
            "Partition %s: %s",
            self.LABELS["root"],
            self.partitions.get(self.LABELS["root"], None),
        )
        log.info(
            "Partition %s: %s",
            self.LABELS["log"],
            self.partitions.get(self.LABELS["log"], None)
        )
        log.info(
            "Partition %s: %s",
            self.LABELS["data"],
            self.partitions.get(self.LABELS["data"], None),
        )
        log.info(
            "Partition %s: %s",
            self.LABELS["images"],
            self.partitions.get(self.LABELS["images"], None),
        )
        log.info(
            "Partition %s: %s",
            self.LABELS["esp"],
            self.partitions.get(self.LABELS["esp"], None)
        )



def main():
    import argparse

    parser = argparse.ArgumentParser(
        description="Perform disk and partition detection for the modian first install scripts"
    )
    parser.add_argument(
        "--version", action="version", version="$(prog)s {}".format(VERSION)
    )
    parser.add_argument(
        "--debug", action="store_true", help="debugging output"
    )
    parser.add_argument(
        "-v", "--verbose", action="store_true", help="verbose output"
    )
    parser.add_argument("--uefi", action="store_true", help="UEFI system")

    args = parser.parse_args()

    if args.debug:
        log_level = logging.DEBUG
    elif args.verbose:
        log_level = logging.INFO
    else:
        log_level = logging.WARN
    logging.basicConfig(
        level=log_level,
        stream=sys.stderr,
        format="%(asctime)s %(levelname)s %(message)s",
    )

    hardware = modian_install.hardware.Hardware()
    system = System(hardware)
    system.detect()

    def print_env(k, v):
        print("{}={}".format(k, shlex.quote(v)))

    print_env("DISK_ROOT", system.disk_root.name)
    if system.disk_img is not None:
        print_env("DISK_IMG", system.disk_img.name)
    else:
        print_env("DISK_IMG", "")
    print_env("DISK_INST", system.disk_inst.name)
    if LABEL_ROOT in system.partitions:
        print_env("PART_ROOT", system.partitions[LABEL_ROOT].dev)
    if LABEL_LOG in system.partitions:
        print_env("PART_LOG", system.partitions[LABEL_LOG].dev)
    if LABEL_DATA in system.partitions:
        print_env("PART_DATA", system.partitions[LABEL_DATA].dev)
    if LABEL_IMAGES in system.partitions:
        print_env("PART_IMAGES", system.partitions[LABEL_IMAGES].dev)
    if LABEL_ESP in system.partitions:
        print_env("PART_ESP", system.partitions[LABEL_ESP].dev)
    print("ACTIONS={}".format(shlex.quote(" ".join(system.compute_actions()))))


if __name__ == "__main__":
    try:
        main()
    except modian_install.actions.ModianError as e:
        log.error("%s", e)
        sys.exit(1)
