#!/usr/bin/python3

import logging
import sys
import os
import re
import shlex

import modian_install

log = logging.getLogger()

VERSION = "1.0"

LABEL_ROOT = "##root##"
LABEL_LOG = "##log##"
LABEL_DATA = "##data##"
LABEL_IMAGES = "##images##"
LABEL_ESP = (
    "##ESP##"  # Not really a disk label, but used to identify ESP partition
)


if __name__ == "__main__":
    pass
