#!/bin/bash

# This is a temporary script that runs one action passed as $1 using the code
# in $DATADIR/common.sh.
# It is run by the python installer script to run the code that it hasn't been
# migrated to python yet, until there will be none and it will be deleted.

set -e

DATADIR=/usr/share/modian-install

. $DATADIR/common.sh

progress "Running action $1"
$1
