#!/usr/bin/env python3

import os
import re
import subprocess

import modian

class Cmd:
    def __init__(self):
        self.config = modian.config.Config()
        self.config.load()

    def main(self):
        grub_cfg = "/live/image/boot/grub/grub.cfg"
        subprocess.run(["mount", "-o", "remount,rw", "/live/image"])
        with open(grub_cfg, "r") as fp:
            grub_conf = fp.read()
        patt = re.compile("set start_unit=.*")
        grub_conf = patt.sub(
            "set start_unit={}".format(self.config.systemd_target),
            grub_conf
        )
        with open(grub_cfg + ".new", "w") as fp:    
            fp.write(grub_conf)
        os.rename(grub_cfg + ".new", grub_cfg)
        subprocess.run(["mount", "-o", "remount,ro", "/live/image"])

if __name__ == "__main__":
    Cmd().main()
