---
- name: Install custom packages
  apt:
    name: cowsay,fortune
    state: present
- name: Install the custom installation script
  copy:
    src: install.py
    dest: /etc/modian/install.py
    mode: 0755
