---
- name: Add the modian repository
  apt_repository:
    repo: 'deb {{ modian_repo }} {{ distribution }} main'
    state: present
- name: Install modian packages
  apt:
    name: modian-install
    state: present
- name: Install the custom installation script
  copy:
    src: install.py
    dest: /etc/modian/install.py
    mode: 0755
