---
 - name: install live packages
   apt:
     name: initramfs-tools,live-boot,live-config,sudo,acpid
     state: present
 - name: blacklist bochs-drm
   copy:
     dest: /etc/modprobe.d/qemu-bochs-drm-blacklist.conf
     content: "blacklist bochs-drm"
