---
 - name: install live packages
   apt:
     name: live-boot,live-config,acpid
     state: present
 - name: blacklist bochs-drm
   copy:
     dest: /etc/modprobe.d/qemu-bochs-drm-blacklist.conf
     content: "blacklist bochs-drm"
