persistence: /srv/persistence.qcow2
persistence_parted: /etc/modian/partitions/small_persistence.parted
nic:
  - "tap,id=eth0,model=e1000,mac=52:54:00:00:00:11"
  - "bridge,id=eth1,br=br0,model=e1000,mac=52:54:00:00:00:01"
# This example will probably run inside a virtual machine, so we need to use
# *very* conservative settings.
qemu_mem: "1G"
qemu_smp: "1"
