#!/usr/bin/perl

# Read the volume ID of a modian USB key
#
# Usage:
#     ./readvolid /dev/sd?

use strict;
use warnings;

die "Use: $0 <iso_file> <new volume id>\n" unless @ARGV == 1;
open my $file, "+<", $ARGV[0] or die "Cannot open: $!";
seek $file, 0x8028,0;
read $file, my $volID, 32;
print $volID, "\n";
